# ─────────────────────────────────────────────────────────────────────────────
# embedder.py  —  TEXT EMBEDDING
#
# Converts text (code) into vectors (lists of numbers) using Voyage AI's API.
# These vectors represent the MEANING of the code, not just the words.
#
# WHY vectors:
#   A vector is a list of 1024 numbers (e.g. [0.21, -0.54, 0.87, ...])
#   Similar meaning → similar numbers → close together in vector space
#   This is what allows semantic search:
#     "find authentication logic" can match "verify_token()" even though
#     the word "authentication" doesn't appear in the function name.
#
# MODEL: voyage-code-2 (Voyage AI)
#   - Trained specifically on code + natural language pairs
#   - Produces 1536-dimensional vectors
#   - Supports asymmetric search: different modes for indexing vs querying
#       input_type="document" → used when embedding code chunks for storage
#       input_type="query"    → used when embedding the user's search query
#     This asymmetry is why scores are higher than general-purpose models
#   - Free tier: 200M tokens/month
#
# FLOW:
#   chunk content (string) → Voyage AI API → vector (list of 1024 floats)
#   This vector is then saved in Pinecone with the chunk's metadata.
# ─────────────────────────────────────────────────────────────────────────────

import os
import voyageai
from dotenv import load_dotenv

# Load API keys from backend/.env file
load_dotenv()

# Initialize the Voyage AI client once (reused for all requests)
_client = voyageai.Client(api_key=os.getenv("VOYAGE_API_KEY"))


def embed_text(text: str) -> list:
    """
    Embeds a single search query into a vector using Voyage AI.
    Uses input_type="query" — optimized for natural language search queries.
    Returns a list of 1024 floats.
    """
    result = _client.embed(
        [text[:8000]],
        model="voyage-code-2",
        input_type="query",   # query mode: optimized for searching
    )
    return result.embeddings[0]


def _build_embed_text(chunk: dict) -> str:
    """
    Builds the text to embed for a chunk.
    Combines three layers for maximum semantic accuracy:

      1. Label     → "Function: getAllProducts"
      2. Summary   → "Fetches all products from the database and returns them as an array."
                     (generated by Claude before embedding — bridges English ↔ code)
      3. Code      → the actual source code

    The summary layer is the key improvement: without it, the embedding only
    sees syntax. With it, natural language queries match with much higher scores.
    If no summary was generated (e.g. LLM failed), falls back to label + code only.
    """
    label   = f"{chunk.get('type', 'function').capitalize()}: {chunk.get('name', '')}"
    summary = chunk.get("summary", "")
    if summary:
        return f"{label}\n{summary}\n{chunk['content'][:8000]}"
    return f"{label}\n{chunk['content'][:8000]}"


def embed_chunks(chunks: list) -> list:
    """
    Embeds a list of code chunks in ONE batched API call.
    Uses input_type="document" — optimized for code documents being indexed.

    The distinction between "document" and "query" modes is key to Voyage AI's
    higher accuracy: code chunks are embedded as documents, search queries as
    queries. This asymmetric approach significantly improves cosine similarity scores.

    Input:  [{ id, name, content, file, ... }]
    Output: [{ id, name, content, file, ..., vector: [0.21, -0.54, ...] }]
    """
    if not chunks:
        return []

    # Prepend type + name to each chunk before embedding
    # This improves semantic matching between natural language queries and function names
    texts = [_build_embed_text(chunk) for chunk in chunks]

    # One API call for all chunks — Voyage AI returns vectors in the same order
    result = _client.embed(
        texts,
        model="voyage-code-2",
        input_type="document",   # document mode: optimized for code being indexed
    )

    # Pair each chunk with its vector by index (order is preserved by Voyage AI)
    output = []
    for chunk, embedding in zip(chunks, result.embeddings):
        output.append({**chunk, "vector": embedding})

    return output
