# ─────────────────────────────────────────────────────────────────────────────
# pinecone_client.py  —  VECTOR DATABASE CLIENT
#
# Handles saving and deleting vectors in Pinecone.
# Pinecone is the cloud database that stores all the embeddings.
#
# WHAT Pinecone stores for each chunk:
#   id       → unique identifier: "src/auth.py::verify_token"
#   values   → the vector: [0.21, -0.54, 0.87, ...] (1536 numbers)
#   metadata → extra info about the chunk:
#                file       → which file it came from
#                name       → function name
#                type       → "function" or "file" (classes are excluded from indexing)
#                start_line → where it starts in the file
#                end_line   → where it ends
#                content    → first 1000 chars of the function (for displaying results)
#                summary    → plain English description generated by Claude at index time
#                             used to display context in search results
#
# TWO OPERATIONS:
#   upsert_chunks → save new vectors (or overwrite if ID already exists)
#   delete_chunks → remove vectors by their IDs (used when code is deleted/changed)
#
# NOTE: metadata field sizes
#   content is capped at 1000 chars — enough to show a preview in results.
#   summary is capped at 300 chars — the Claude-generated plain English description.
#   The full source is always on disk; file + line numbers get you there.
# ─────────────────────────────────────────────────────────────────────────────

import os
from pinecone import Pinecone
from dotenv import load_dotenv

# Load API keys from backend/.env file
load_dotenv()

# Initialize Pinecone client and connect to our index
_pc    = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
_index = _pc.Index(host=os.getenv("PINECONE_HOST"))  # index host URL from Pinecone dashboard


def upsert_chunks(chunks_with_vectors: list, namespace: str):
    """
    Saves a list of embedded chunks to Pinecone under the given namespace.
    namespace = "{projectId}::{userId}" — keeps each user's vectors isolated.
    "Upsert" = insert if new, update if ID already exists.

    Each chunk must have: id, vector, file, name, type, start_line, end_line, content
    """
    vectors = []
    for chunk in chunks_with_vectors:
        vectors.append({
            "id":     chunk["id"],      # e.g. "src/auth.py::verify_token"
            "values": chunk["vector"],  # the 1536-float embedding
            "metadata": {
                "file":       chunk["file"],
                "name":       chunk["name"],
                "type":       chunk["type"],
                "start_line": chunk["start_line"],
                "end_line":   chunk["end_line"],
                "content":    chunk["content"][:1000],  # Pinecone metadata size limit
                "summary":    chunk.get("summary", "")[:300],  # LLM-generated plain English description
            },
        })

    if vectors:
        _index.upsert(vectors=vectors, namespace=namespace)


def delete_chunks(chunk_ids: list, namespace: str):
    """
    Removes vectors from Pinecone by their IDs within the given namespace.
    Called when:
      - A function was deleted from a file
      - A function's content changed (delete old vector, upsert new one)
      - A whole file was deleted
    """
    if chunk_ids:
        _index.delete(ids=chunk_ids, namespace=namespace)


def query_chunks(vector: list, namespace: str, top_k: int = 10) -> list:
    """
    Searches Pinecone for the most semantically similar vectors to the given query vector.
    Returns the top_k closest matches with their metadata.

    This is the core of AI search:
      1. The user's query is embedded into a vector (in server.py)
      2. Pinecone compares that vector against all stored function vectors
      3. Returns the closest matches (highest cosine similarity score)

    Each result contains: id, score, file, name, type, start_line, end_line, content
    """
    result = _index.query(
        vector=vector,
        top_k=top_k,
        namespace=namespace,
        include_metadata=True,
    )

    matches = []
    for match in result.matches:
        matches.append({
            "id":         match.id,
            "score":      round(match.score, 4),
            "file":       match.metadata.get("file", ""),
            "name":       match.metadata.get("name", ""),
            "type":       match.metadata.get("type", ""),
            "start_line": int(match.metadata.get("start_line", 0)),
            "end_line":   int(match.metadata.get("end_line", 0)),
            "content":    match.metadata.get("content", ""),
            "summary":    match.metadata.get("summary", ""),
        })
    return matches
